# Generated by Django 5.2.6 on 2026-02-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_internalnote_and_closedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalticketnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
