# Generated by Django 5.2.6 on 2026-02-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_alter_internalticketnote_id_alter_ticket_status'),
        ('support', '0012_profile_phone'),
    ]

    operations = [
    ]
