# Generated by Django 5.2.6 on 2026-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
