# Generated by Django 5.2.6 on 2026-05-24 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_ticket_attachment_alter_profile_role_activitylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='engineer_notes',
            field=models.TextField(blank=True, help_text='Internal engineering notes and troubleshooting steps. Not visible to customers.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_date',
            field=models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Summary of the resolution provided to the customer. Visible after ticket closure.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
